---
# Separate the workflow for actionlint to other workflows, because if a workflow for actionlint is broken actionlint isn't run
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
jobs:
  status-check:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: suzuki-shunsuke/actionlint-action@ef913b89058e81a18703bb8db1ab70c51d82523a # v0.0.1
