---
name: renovate-config-validator
on:
  pull_request:
    paths:
      - renovate.json5
      - .github/workflows/renovate-config-validator.yaml
jobs:
  status-check:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: suzuki-shunsuke/renovate-config-validator-action@51b62d3bf0c86d4de68c580a057c1e16f0702d07 # v0.0.1
