---
name: test
on: pull_request
permissions: {}
concurrency:
  group: ${{ github.workflow }}--${{ github.ref }}
  cancel-in-progress: true
jobs:
  status-check:
    uses: ./.github/workflows/wc-status-check.yaml
    permissions: {}
    if: always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'))
    needs:
      - test
  test:
    uses: ./.github/workflows/wc-test.yaml
    permissions: {}
