---
name: test
on: pull_request
permissions: {}
concurrency:
  group: ${{ github.workflow }}--${{ github.ref }}
  cancel-in-progress: true
jobs:
  status-check:
    uses: ./.github/workflows/wc-status-check.yaml
    permissions: {}
    if: failure()
    needs:
      - test
  test:
    uses: ./.github/workflows/wc-test.yaml
    permissions: {}
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
